service: spotifyapi

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512
  timeout: 10

functions:
  spotify:
    handler: lambda.handler
    events:
      - http: ANY spotify
        # - http: ANY /spotify
        method: any
        cors:
          headers: "*"
  callback:
  handler: lambda.handler
  events:
    - http: GET spotify
      path: spotify/callback
      # - http: ANY /spotify
      method: any
      cors:
        headers: "*"
  hello:
    handler: lambda.hello
    events:
      - http: GET hello # this is the API gateway event
        path: hello
        method: get
        cors:
          header: "*"
  goodbye:
    handler: lambda.hello
    events:
      - http: GET goodbye # this is the API gateway event
        path: goodbye
        method: get
        cors:
          header: "*"
